// const url =
const token =
  `eyJ4NWMiOlsiTUlJQytUQ0NBcCtnQXdJQkFnSUJBREFLQmdncWhrak9QUVFEQWpCR01VUXdRZ1lEVlFRREV6c3lWMDVaT2xWTFMxSTZSRTFFVWpwU1NVOUZPa3hITmtFNlExVllWRHBOUmxWTU9rWXpTRVU2TlZBeVZUcExTak5HT2tOQk5sazZTa2xFVVRBZUZ3MHlNREF4TURZeU1EVXhNVFJhRncweU1UQXhNalV5TURVeE1UUmFNRVl4UkRCQ0JnTlZCQU1UTzFWQlVUYzZXRk5PVXpwVVIxUXpPa0UwV2xVNlNUVkhTenBTTmpSWk9sZERTRU02VjFaU1N6cE5TVE5TT2t0WVRUYzZTRmRUTXpwQ1ZscGFNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXJ4eTJvbkgwU1h4eGtSQmRvcFgxVnNVbkFaXC85SllHck1JeWt6Um4xNGx3UDVKRWYrWE01QU5FbU1cLzBYOFJyNUlIN2VTWFV6K1lWaFVucVNKc3lPUlwvcXdwU3hXS1lMcVZwdW5RTlk4SGs3ZkZ5bzdJdG14MWo2dXZ0bVZhYmxRT0xGSTFCTVZ2NmNyMVY1d0ZWUWFnN0p4ZEVBUmVrWkdTOXg5SHJzNTVXcW9JUitvRkRsMVVUYzZQRUo2VVhncGJoV1h2aFNET2lwT3FJWHR2ZHRyaFhRaXdtOGNxMnMxdExEM2c4NlpkWFRYN1AxRWZMRThtYzBIeGpwRjZHYjVsR2RYY3Y1OXBcL1IzMVwva0xlXC9PcERzZ1VicTBBb3dwbHNZS29HZUpnVTQyWmRuOUhWRlFRUXBLRkxQTStaUDdEdmZlRjFjSFhYRm5SNU5KRVNWdWxUUUlEQVFBQm80R3lNSUd2TUE0R0ExVWREd0VCXC93UUVBd0lIZ0RBUEJnTlZIU1VFQ0RBR0JnUlZIU1VBTUVRR0ExVWREZ1E5QkR0VlFWRTNPbGhUVGxNNlZFZFVNenBCTkZwVk9razFSMHM2VWpZMFdUcFhRMGhET2xkV1VrczZUVWt6VWpwTFdFMDNPa2hYVXpNNlFsWmFXakJHQmdOVkhTTUVQekE5Z0RzeVYwNVpPbFZMUzFJNlJFMUVVanBTU1U5Rk9reEhOa0U2UTFWWVZEcE5SbFZNT2tZelNFVTZOVkF5VlRwTFNqTkdPa05CTmxrNlNrbEVVVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBeXlISklTVFlzWnZlVnI1YTVjNngyOGtDZTkzbDVCd1BUZFROT1JoUHRzRUNJRExHelh1TG56RGpMK3NxZGQ5TkVuRG4ydnZQUFZWTU1cLzhDQW1EaTVudnMiXSwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJzZXNzaW9uX2lkIjoiRDE0NDkwOUZEMEMxOTE0OUNBQjVERDdBREVBOTM4ODIiLCJpYXQiOjE2MDMwOTQ1MTgsImV4cCI6MTYwNTY4NjUxOCwic3ViIjoiMjk2ZGVmZjY3ZTJiNDI4MzkzMzliZjliMzJmYmY5MWMiLCJ1c2VybmFtZSI6InNoaW5od2FnayIsImp0aSI6IkQxNDQ5MDlGRDBDMTkxNDlDQUI1REQ3QURFQTkzODgyIiwidXNlcl9pZCI6IjI5NmRlZmY2N2UyYjQyODM5MzM5YmY5YjMyZmJmOTFjIiwiZW1haWwiOiIifQ.GsYHOuTJ22YyTEQ1ZxqVaeaBUCHTM8eRms4lOXFrYcOyAwQQb_AX4n72EnZA2ozmkSQuTP0e-IPSXL5sga7KCHC7tRHXk1PI_wcM6Yjdc8A91emYx2r5YQ9R-PCJEiaxUonDUYqmstcOxNDP_CaLgmiWv_qz9Fk4bTA2lN3Smud2Uq1hqM3C3m9VKaa6c5gUXSDRX_5T9QsOamuBHkBAmMrSxKk2PxnvY1j6rT1Z8CGuX_Zv05DWwJmTM2CYzL16lfte_ODZt_pmEAWyLb4SakNwuFgPtFxrf4S1Kh9fEl2g370CRAJ_ZIuuqqnUkJes5egnW72W3l-IDj9IbXYlqA`;
// const url = new URL(
//   `https://cloud.docker.com/v2/repositories/shinhwagk/test/tags/1.0/`,
// );
// url.username = "shinhwagk";
// url.password = "A37956LSZX";
const x = await fetch(
  "https://hub.docker.com/v2/repositories/shinhwagk/test/tags/1.0/",
  { method: "DELETE", headers: { Authorization: `JWT ${token}` } },
);

console.log(x.status);
console.log(await x.text());

// https:
// //hub.docker.com/v2/users/login/

// const x = await fetch("https://hub.docker.com/v2/users/login/", {
//   method: "POST",
//   headers: { "content-type": "application/json" },
//   body: JSON.stringify({
//     username: "shinhwagk",
//     password: "A37956LSZX",
//   }),
// });
// console.log(x.status);
// console.log(await x.text());
