name: ci

on:
  push:
    branches: master

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: ls -l /home/runner/work/gitbuild/gitbuild/.github/actions/parse/index.js
      - id: step1
        uses: ./.github/actions/parse
  job2:
    needs: job1
    strategy:
      matrix:
        key: ${{fromJson(needs.job1.outputs.output1)}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with: ${{matrix.key}}
      - run: docker images
#       - name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}
