name: ci

on:
  push:
    branches: master

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::[\"a\",\"b\"]"
      - id: step2
        run: echo "::set-output name=test::[\"a1\",\"b1\"]"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        key: ${{fromJson(needs.job1.outputs.output1)}}
        val: ${{fromJson(needs.job1.outputs.output2)}}
    steps:
    - run: |
        echo -ne ${{matrix.key}}
        echo -ne ${{matrix.val}}`
      # - name: Checkout
      #   uses: actions/checkout@v2
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
