name: ci

on:
  push:
    branches: master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - run: echo  ${{steps.step1.outputs}}
      - run: echo  ${{steps.step1.outputs.test}}
      - run: echo  ${{join(steps.step1.outputs.*, '\n')}}
      - id: step2
        run: echo "::set-output name=test::hello\nabc"
      - run: echo -e ${{steps.step2.outputs}}
      - run: echo -e ${{steps.step2.outputs.test}}
      - run: echo -e ${{join(steps.step2.outputs.*, '\n')}}
      # - name: Checkout
      #   uses: actions/checkout@v2
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
