name: ci

on:
  push:
    branches: master

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::[\"images/1.0.0\"]"
  job2:
    needs: job1
    strategy:
      matrix:
        key: ${{fromJson(needs.job1.outputs.output1)}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          context: images/1.0.0
          file: images/1.0.0/Dockerfile
          tags: |
            user/app:latest
            user/app:1.0.0
      - run: docker images
#       - name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}
